### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by jlwatkins** [dustinpoissant/AddSlider#1]
If I want to reset the values for data-min and data-max, etc, etc. via javascript. What is the best way to refresh this element. I am having problems redrawing the element with html and js.

**Comment by dustinpoissant** [comment]
My understanding of the question is that you would like to change the min/max after the slider has already been initialized, is this correct?

If this is what you are asking then you will need a reference to the JS slider object itself. So you must initialize it use JavaScript rather than the standard HTML method.

```html
<input id='mySlider' />
```

```JavaScript
$(function(){
  var slider = $add.Slider("#mySlider", {
    /* settings here */
    min: 0,
    max: 10,
    step: 1
  });
});
```

And then at a later time you can update those values using:

```JavaScript
slider.settings.min = 5;
slider.settings.max = 20;
slider.refresh();
```
